{
 "title": "Kubernetes / API servers",
 "tags": [
  "kubernetes",
  "api"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(apiserver_request_total, cluster)"
   },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(apiserver_request_total{component=\"apiserver\", cluster=\"$cluster\"}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(apiserver_request_total{job=\"$job\", cluster=\"$cluster\"}, instance)"
   },
   {
    "name": "interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by (namespace, instance, pod, gitVersion, buildDate) (kubernetes_build_info{service=\"kubelet\", namespace=\"kube-system\"})"
    }
   ]
  },
  {
   "title": "Servers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(up{job=\"$job\", cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{cluster=\"$cluster\",job=\"$job\",instance=~\"$instance\",service=\"kubernetes\"}\n) * 1000"
    }
   ]
  },
  {
   "title": "RPC Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$job\", instance=~\"$instance\",code=~\"2..\", cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "2xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$job\", instance=~\"$instance\",code=~\"3..\", cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "3xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$job\", instance=~\"$instance\",code=~\"4..\", cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "4xx"
    },
    {
     "expr": "sum(rate(apiserver_request_total{job=\"$job\", instance=~\"$instance\",code=~\"5..\", cluster=\"$cluster\"}[$interval]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Request duration 99th quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(apiserver_request_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\", verb!=\"WATCH\", cluster=~\"$cluster\"}[$interval])) by (verb, le))",
     "legendFormat": "{{verb}}"
    }
   ]
  },
  {
   "title": "Availability (30d) > 99.000",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\"}"
    }
   ]
  },
  {
   "title": "ErrorBudget (30d) > 99.000",
   "type": "graph",
   "gridPos": { "h": 7, "w": 20, "x": 4, "y": 12 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "100 * (apiserver_request:availability30d - 0.990000)",
     "legendFormat": "errorbudget"
    }
   ]
  },
  {
   "title": "Read Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"read\"}"
    }
   ]
  },
  {
   "title": "Read SLI - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{verb=\"read\"})"
    }
   ]
  },
  {
   "title": "Read SLI - Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 19 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{verb=\"read\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Read SLI - Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\",code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"read\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write Availability (30d)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"write\"}"
    }
   ]
  },
  {
   "title": "Write SLI - Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(code_resource:apiserver_request_total:rate5m{verb=\"write\"})"
    }
   ]
  },
  {
   "title": "Write SLI - Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 11, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "cluster_quantile:apiserver_request_duration_seconds:histogram_quantile{verb=\"write\"}",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Write SLI - Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 26 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\",code=~\"5..\"}) / sum by (resource) (code_resource:apiserver_request_total:rate5m{verb=\"write\"})",
     "legendFormat": "{{ resource }}"
    }
   ]
  },
  {
   "title": "Work Queue Add Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Depth [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(workqueue_depth{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance, name)",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "Work Queue Latency [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance, name, le))",
     "legendFormat": "{{instance}} {{name}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Entry Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "etcd_helper_cache_entry_total{job=\"$job\", instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "ETCD Cache Hit/Miss Rate [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(etcd_helper_cache_hit_total{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} hit"
    },
    {
     "expr": "sum(rate(etcd_helper_cache_miss_total{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance)",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "ETCD Cache Duration 99th Quantile [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_cache_get_duration_seconds_bucket{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance, le))",
     "legendFormat": "{{instance}} get"
    },
    {
     "expr": "histogram_quantile(0.99,sum(rate(etcd_request_cache_add_duration_seconds_bucket{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[$interval])) by (instance, le))",
     "legendFormat": "{{instance}} miss"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"$job\",instance=~\"$instance\", cluster=\"$cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}