{
 "title": "kubernetes / CoreDNS",
 "description": "Kubernetes CoreDNS Dashboard",
 "tags": [
  "prometheus",
  "dns",
  "coredns",
  "kubernetes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(coredns_build_info, cluster)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(coredns_build_info{cluster=\"$cluster\"}, pod)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Up Time",
   "type": "stat",
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(process_start_time_seconds{cluster=\"$cluster\",pod=~\"$pod\"}) * 1000"
    }
   ]
  },
  {
   "title": "Requests/s [1m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Hits/s [1m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{cluster=\"$cluster\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Size/s",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Pods",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{container=\"coredns\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Cache Misses/s [1m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$cluster\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Success Cache Hits [1m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"success\",cluster=\"$cluster\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Denial Cache Hits [1m]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"denial\",cluster=\"$cluster\",pod=~\"$pod\"}[1m]))"
    }
   ]
  },
  {
   "title": "Cache Size Success",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{type=\"success\",cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Cache Size Denial",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(coredns_cache_entries{type=\"denial\",cluster=\"$cluster\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Version",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "count by (namespace, instance, pod, version,goversion) (coredns_build_info{container=\"coredns\", namespace=\"kube-system\",cluster=\"$cluster\"})\n"
    }
   ]
  },
  {
   "title": "Request duration [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(rate(coredns_dns_request_duration_seconds_bucket{cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "request - max delay"
    },
    {
     "expr": "max(rate(coredns_forward_request_duration_seconds_bucket{cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "forward - max delay"
    }
   ]
  },
  {
   "title": "Requests/s (by pod) [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Requests (by qtype) [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (type)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Requests/s (by Protocol) [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (proto)",
     "legendFormat": "{{ proto }}"
    }
   ]
  },
  {
   "title": "Requests (size, udp) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests Forward/s (by pod) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 18 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Requests (size,tcp) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:99 "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_request_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto))",
     "legendFormat": "{{proto}}:50"
    }
   ]
  },
  {
   "title": "Requests w/ DNSSEC OK [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 18 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_requests_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Responses (size, udp) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"udp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses Forward/s (by pod) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_forward_responses_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (pod)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Responses (size, tcp) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}:99%"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le,proto)) ",
     "legendFormat": "{{proto}}:90%"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(coredns_dns_response_size_bytes_bucket{proto=\"tcp\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (le, proto)) ",
     "legendFormat": "{{proto}}:50%"
    }
   ]
  },
  {
   "title": "Responses (by rcode) [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "yaxes": [
    { "format": "pps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_dns_responses_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval])) by (rcode)",
     "legendFormat": "{{rcode}}"
    }
   ]
  },
  {
   "title": "Cache (Hits) [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"success\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "hits: success"
    },
    {
     "expr": "sum(rate(coredns_cache_hits_total{type=\"denial\",cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "hits: denial"
    }
   ]
  },
  {
   "title": "Cache (Misses) [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(coredns_cache_misses_total{cluster=\"$cluster\",pod=~\"$pod\"}[$interval]))",
     "legendFormat": "misses"
    }
   ]
  }
 ]
}