{
 "title": "Infrastructure / Nodes",
 "description": "Node Resources",
 "tags": [
  "kube-visibility",
  "nodes"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(node_exporter_build_info{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(\n  (1 - rate(node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"$instance\"}[$interval]))\n/ ignoring(cpu) group_left\n  count without (cpu)( node_cpu_seconds_total{job=\"node-exporter\", mode=\"idle\", instance=\"$instance\"})\n)\n",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "1m load average"
    },
    {
     "expr": "node_load5{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "5m load average"
    },
    {
     "expr": "node_load15{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "15m load average"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=\"node-exporter\", instance=\"$instance\", mode=\"idle\"})",
     "legendFormat": "logical cores"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}\n-\n  node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}\n-\n  node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}\n-\n  node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"}\n)\n",
     "legendFormat": "memory used"
    },
    {
     "expr": "node_memory_Buffers_bytes{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "memory buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "memory cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{job=\"node-exporter\", instance=\"$instance\"}",
     "legendFormat": "memory free"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 -\n(\n  node_memory_MemAvailable_bytes{job=\"node-exporter\", instance=\"$instance\"}\n/\n  node_memory_MemTotal_bytes{job=\"node-exporter\", instance=\"$instance\"}\n* 100\n)\n"
    }
   ]
  },
  {
   "title": "Disk Space Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 19, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}\n  -\n    node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "used"
    },
    {
     "expr": "sum(\n  max by (device) (\n    node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}\n  )\n)\n",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  avg(avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}[$__range]))\n  -\n  avg(avg_over_time(node_filesystem_avail_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}[$__range]))\n)\n/\navg(avg_over_time(node_filesystem_size_bytes{job=\"node-exporter\", instance=\"$instance\", fstype!=\"\"}[$__range]))\n* 100\n"
    }
   ]
  },
  {
   "title": "Disk I/O [$interval]",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{job=\"node-exporter\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{job=\"node-exporter\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$interval])",
     "legendFormat": "{{device}} written"
    },
    {
     "expr": "rate(node_disk_io_time_seconds_total{job=\"node-exporter\", instance=\"$instance\", device=~\"nvme.+|rbd.+|sd.+|vd.+|xvd.+|dm-.+|dasd.+\"}[$interval])",
     "legendFormat": "{{device}} io time"
    }
   ]
  },
  {
   "title": "Network Received [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{job=\"node-exporter\", instance=\"$instance\", device!=\"lo\"}[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Network Transmitted [$interval]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_transmit_bytes_total{job=\"node-exporter\", instance=\"$instance\", device!=\"lo\"}[$interval])",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}